name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller -r requirements.txt
      - run: pyinstaller --onefile --windowed --hidden-import=openpyxl --hidden-import=pandas --hidden-import=watchdog.observers.winapi --hidden-import=tracker --name "WoTTracker" main1.py
      - uses: actions/upload-artifact@v4
        with:
          name: WoTTracker-windows
          path: dist/WoTTracker.exe
